"""empty message

Revision ID: 856ea1cf3fbf
Revises: ea8b89feb277
Create Date: 2021-12-12 22:47:10.440686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856ea1cf3fbf'
down_revision = 'ea8b89feb277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('chances', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'chances')
    # ### end Alembic commands ###
