"""empty message

Revision ID: ea8b89feb277
Revises: 319ac22cc8dc
Create Date: 2021-12-12 15:07:00.104394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8b89feb277'
down_revision = '319ac22cc8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'created_at')
    # ### end Alembic commands ###
